name: Deploy doc to gh-pages

on:
  push:
    branches:
      - main

jobs:
  deploy-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use OCaml 4.14.x
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.14.x
          dune-cache: true

      - run: opam install dune

      - name: Build documentation
        run: opam exec -- dune build @doc

      - name: Deploy odoc to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ github.token }}
          publish_dir: _build/default/_doc/_html
          destination_dir:
          enable_jekyll: false
